import myrustlib

seq = "GTCGATGAAGTCCCTTGATGGTCTAGCTAAAAGGGTTCGTGGGCCGTCCTGGCGGTTGGCGAGTGCAGTATGTGGGCGCGTGCGGCGAAAACTTGTCGAAACATCTATCAGGCATTACCCGCCCCCTTGTCACCGGGTATATCGCAGTCCATACTTCGCGGCGTGCGCGCGTAGGTCTGGAATTAGGTCAGTGGGGGACCACGGACTCTACATAAGACCTACGCGTCTGCTATTCGTGTCGGAGGGAAAAAGACTGATAATGGCTGCAGTGGTCACTTTAGGTTCTCTATCTGAGTTGGTGTCGGATACTCGTGATTTCCCGCCTTGGCTCCCGTATTTGTTAAAATCCGGATTCAAAGGAATCTTATTTAGGATAGCTAGTTGTCTTAAACAGGCTCGTGTCGTCATTCGGTAGAAGCTCTTTCATTGGCTGTAAGAGATTACCGTATGCACCCGCAAGTAGTAGGAAGTCTGCCCGACCTTTCGATCAATTAATGTTAGAGGATATCCGATCACAATATCTATTTTCTTTATATCTATCCATCGCAACAGGTAACCTGCCAATGTATCCCGAGTTCGATAGACATGACATCTTGAACCAGGGCTGGGGTCACCTAGTGGCGATCCGGGTCACGGGACACACCTCCTGAGGGCAGAAAAGCTCCATAGATCTTCGGTTGACTCGACTCATTAAGCTAAATGTTGCATACTGTGCGGAGCCTCCTGACCGTCTTCATTTAGAGGAAGGAGCGTACATGTATTGTTCACACGCTCTGAAAGTACGGAGCTGAGCGCAGGAGATGACGCACCCGAGCTCCTGGTCAACTTTATGGAACACCACTGCTATCGCCAATGCCATTGCCCAATAGGACGGGTATAAAAGCGCAAAGTCTACCGTGCAGCGTGGACCCCGCCCCTGACTCTACGTTACCGGCACGACAGCGTAATTTGGCGTACGTCCTGTTCTTAACTGGCCTCTAAGGCCCGACTAGGACCCGTG"

def gc_content(seq: str) -> float:
  return (seq.count("G") + seq.count("C")) / len(seq)

# =============== Benchmark ===============

def test_original_version(benchmark):
  benchmark(gc_content, seq)

def test_rust_version(benchmark):
  benchmark(myrustlib.gc_content, seq)

def test_rust_version_v2(benchmark):
  benchmark(myrustlib.gc_content_v2, seq)

# ================== Main =================

def main():
  print(myrustlib)
  print(help(myrustlib))

  print("og:", gc_content(seq))
  print("rust v1:", myrustlib.gc_content(seq))
  print("rust v2:", myrustlib.gc_content_v2(seq))

if __name__ == "__main__":
  main()
